# frozen_string_literal: true

RSpec.describe RubySkills::Adapters::Claude do
  def plant_canonical(root, name, version)
    path = root.join(".ruby-skills", *name.split("/"), version)
    FileUtils.mkdir_p(path)
    path.join("SKILL.md").write("# #{name}\n")
    path.join("skill.yml").write("name: #{name}\nversion: #{version}\n")
    path
  end

  def adapter_skill(root, name, version)
    RubySkills::Adapters::Skill.new(
      name: name,
      version: version,
      path: plant_canonical(root, name, version)
    )
  end

  def project_for(root, skills)
    RubySkills::Adapters::Project.new(root: root, skills: skills)
  end

  describe "#name" do
    it "returns the human-readable agent name" do
      expect(described_class.new.name).to eq("Claude")
    end
  end

  describe "#available?" do
    it "is true when the agent directory exists" do
      with_tmp_project do |root|
        FileUtils.mkdir_p(root.join(".claude"))

        expect(described_class.new(root: root)).to be_available
      end
    end

    it "is false when the agent directory is missing" do
      with_tmp_project do |root|
        expect(described_class.new(root: root)).not_to be_available
      end
    end
  end

  describe "#sync" do
    it "links canonical skills with a relative symlink and a managed marker" do
      with_tmp_project do |root|
        FileUtils.mkdir_p(root.join(".claude"))
        skill = adapter_skill(root, "rails/conventions", "1.3.2")
        adapter = described_class.new(root: root)

        result = adapter.sync(project: project_for(root, [skill]))
        link = root.join(".claude", "skills", "rails-conventions@1.3.2")

        expect(result.added).to eq(["rails/conventions@1.3.2"])
        expect(link).to be_symlink
        expect(link.readlink.to_s).to eq("../../.ruby-skills/rails/conventions/1.3.2")
        expect(link.join("SKILL.md")).to be_file
        expect(root.join(".claude", "skills", ".ruby-skills-managed").read)
          .to include("Generated by ruby-skills")
      end
    end

    it "is idempotent" do
      with_tmp_project do |root|
        FileUtils.mkdir_p(root.join(".claude"))
        skill = adapter_skill(root, "rails/conventions", "1.3.2")
        adapter = described_class.new(root: root)
        adapter.sync(project: project_for(root, [skill]))

        result = adapter.sync(project: project_for(root, [skill]))

        expect(result.added).to be_empty
        expect(result.removed).to be_empty
        expect(result.kept).to eq(["rails/conventions@1.3.2"])
      end
    end

    it "removes stale generated versions without touching user skills" do
      with_tmp_project do |root|
        FileUtils.mkdir_p(root.join(".claude"))
        old = adapter_skill(root, "rails/request-specs", "2.0.0")
        fresh = adapter_skill(root, "rails/request-specs", "2.1.4")
        user = root.join(".claude", "skills", "my-local-skill")
        FileUtils.mkdir_p(user)
        user.join("SKILL.md").write("# mine\n")
        adapter = described_class.new(root: root)
        adapter.sync(project: project_for(root, [old]))

        result = adapter.sync(project: project_for(root, [fresh]))

        expect(result.added).to eq(["rails/request-specs@2.1.4"])
        expect(result.removed).to eq(["rails/request-specs@2.0.0"])
        expect(root.join(".claude", "skills", "rails-request-specs@2.0.0")).not_to exist
        expect(user.join("SKILL.md").read).to eq("# mine\n")
      end
    end

    it "does not modify canonical skill contents" do
      with_tmp_project do |root|
        FileUtils.mkdir_p(root.join(".claude"))
        skill = adapter_skill(root, "rails/conventions", "1.3.2")
        original = skill.path.join("SKILL.md").read

        described_class.new(root: root).sync(project: project_for(root, [skill]))

        expect(skill.path.join("SKILL.md").read).to eq(original)
      end
    end

    it "does not write when dry_run is true" do
      with_tmp_project do |root|
        FileUtils.mkdir_p(root.join(".claude"))
        skill = adapter_skill(root, "rails/conventions", "1.3.2")

        result = described_class.new(root: root).sync(
          project: project_for(root, [skill]),
          dry_run: true
        )

        expect(result.added).to eq(["rails/conventions@1.3.2"])
        expect(root.join(".claude", "skills")).not_to exist
      end
    end

    it "returns unavailable when the agent is missing" do
      with_tmp_project do |root|
        skill = adapter_skill(root, "rails/conventions", "1.3.2")

        result = described_class.new(root: root).sync(project: project_for(root, [skill]))

        expect(result.available).to be false
        expect(root.join(".claude")).not_to exist
      end
    end
  end

  describe "#remove" do
    it "deletes the skill directory under .claude/skills" do
      with_tmp_project do |root|
        destination = root.join(".claude", "skills", "rails-performance")
        FileUtils.mkdir_p(destination)
        destination.join("SKILL.md").write("# skill\n")

        described_class.new(root: root).remove("rails-performance")

        expect(destination).not_to exist
      end
    end

    it "clears managed symlinks for a project" do
      with_tmp_project do |root|
        FileUtils.mkdir_p(root.join(".claude"))
        skill = adapter_skill(root, "rails/conventions", "1.3.2")
        user = root.join(".claude", "skills", "keep-me")
        adapter = described_class.new(root: root)
        project = project_for(root, [skill])
        adapter.sync(project: project)
        FileUtils.mkdir_p(user)

        adapter.remove(project: project)

        expect(root.join(".claude", "skills", "rails-conventions@1.3.2")).not_to exist
        expect(user).to be_directory
      end
    end
  end
end

RSpec.describe RubySkills::Adapters::Cursor do
  it "uses .cursor/skills as the adapter destination" do
    expect(described_class::ADAPTER_INFO).to eq(
      adapter: ".cursor",
      directory: "skills"
    )
  end

  it "is named Cursor" do
    expect(described_class.new.name).to eq("Cursor")
  end
end

RSpec.describe RubySkills::Adapters::Vscode do
  it "uses .vscode/skills as the adapter destination" do
    expect(described_class::ADAPTER_INFO).to eq(
      adapter: ".vscode",
      directory: "skills"
    )
  end

  it "is named VS Code" do
    expect(described_class.new.name).to eq("VS Code")
  end
end

RSpec.describe RubySkills::Adapters::Codex do
  it "uses .codex/skills as the adapter destination" do
    expect(described_class::ADAPTER_INFO).to eq(
      adapter: ".codex",
      directory: "skills"
    )
  end
end

RSpec.describe RubySkills::Adapters do
  describe ".all" do
    it "lists the built-in agent adapters" do
      expect(described_class.all).to eq(
        [
          RubySkills::Adapters::Claude,
          RubySkills::Adapters::Codex,
          RubySkills::Adapters::Cursor,
          RubySkills::Adapters::Vscode
        ]
      )
    end
  end

  describe ".find" do
    it "finds an adapter by id" do
      expect(described_class.find("claude")).to eq(RubySkills::Adapters::Claude)
      expect(described_class.find("vs-code")).to eq(RubySkills::Adapters::Vscode)
    end
  end

  describe ".sync_remove" do
    it "removes the skill from every adapter destination" do
      with_tmp_project do |root|
        destinations = described_class.all.map { |klass|
          info = klass::ADAPTER_INFO
          path = root.join(info.fetch(:adapter), info.fetch(:directory), "rails-performance")
          FileUtils.mkdir_p(path)
          path.join("SKILL.md").write("# skill\n")
          path
        }

        described_class.sync_remove("rails-performance", root: root)

        expect(destinations.map(&:exist?)).to all(be false)
      end
    end
  end
end
