# frozen_string_literal: true

require "fileutils"
require "pathname"

module RubySkills
  # Agent-specific mirrors of canonical +.ruby-skills+ storage.
  #
  # {Adapters.all} lists Claude, Codex, Cursor, and VS Code. Canonical
  # artifacts stay under +.ruby-skills+; adapters only write disposable
  # symlinks into each agent's skills directory.
  module Adapters
    # One locked, installed skill to expose to agents.
    Skill = Struct.new(:name, :version, :path, keyword_init: true) do
      # @return [String] +namespace/name@version+
      def label
        "#{name}@#{version}"
      end
    end

    # Project snapshot passed to {Base#sync} and {Base#remove}.
    Project = Struct.new(:root, :skills, keyword_init: true)

    # Per-adapter sync outcome.
    ChangeSet = Struct.new(:added, :removed, :kept, :available, keyword_init: true) do
      # Labels currently exposed after a successful sync.
      #
      # @return [Array<String>]
      def current
        (Array(kept) + Array(added)).sort
      end
    end

    class << self
      # Adapter classes that mirror canonical storage into agent directories.
      #
      # @return [Array<Class>]
      def all
        [Claude, Codex, Cursor, Vscode]
      end

      # @return [Array<String>]
      def ids
        all.map(&:id)
      end

      # @param id [String]
      # @return [Class, nil]
      def find(id)
        needle = normalize_id(id)
        all.find { |klass| klass.id == needle }
      end

      # Remove +name+ from every adapter destination under +root+.
      #
      # @param name [String]
      # @param root [String, Pathname]
      # @return [void]
      def sync_remove(name, root:)
        all.each do |klass|
          klass.new(root: root).remove(name)
        end
      end

      # @param id [String]
      # @return [String]
      def normalize_id(id)
        id.to_s.downcase.gsub(/[^a-z0-9]/, "")
      end
    end

    # Base implementation for skill adapters.
    #
    # Subclasses must define an ADAPTER_INFO constant containing:
    #
    # - :adapter   — tool directory under the project root
    # - :directory — directory containing skills
    #
    # Optional +DISPLAY_NAME+ overrides the human-readable agent name.
    #
    # @abstract
    # @since 0.1.0
    class Base # rubocop:disable Metrics/ClassLength
      # Marker written next to generated symlinks.
      MANAGED_MARKER = ".ruby-skills-managed"

      MARKER_CONTENTS = <<~TEXT
        # Generated by ruby-skills. Do not edit.
        # Disposable symlinks into .ruby-skills/. Canonical copies are the source of truth.
      TEXT

      class << self
        # @return [String]
        def display_name
          return self::DISPLAY_NAME if const_defined?(:DISPLAY_NAME, false)

          name.split("::").last
        end

        # @return [String]
        def id
          Adapters.normalize_id(display_name)
        end
      end

      # @param root [String, Pathname] project root
      def initialize(root: Dir.pwd)
        @root = Pathname.new(root)
      end

      # @return [String]
      def name
        self.class.display_name
      end

      # @return [String]
      def id
        self.class.id
      end

      # Whether this agent's project directory is present.
      #
      # @return [Boolean]
      def available?
        agent_root.directory?
      end

      # Install a skill into the adapter destination.
      #
      # @param name [String] skill identifier
      # @param source [String, Pathname] source skill path
      # @return [void]
      def install(name, source)
        link(source, destination_for(name))
      end

      # Expose +project+ skills to this agent. No-op when the agent is absent.
      #
      # @param project [Project]
      # @param dry_run [Boolean]
      # @return [ChangeSet]
      def sync(project:, dry_run: false)
        return unavailable_change_set unless available?

        wanted = Array(project.skills)
        current = managed_entries
        changeset = diff(wanted, current)
        apply(wanted, current, changeset) if !dry_run && apply?(changeset)
        changeset
      end

      # Drop generated entries.
      #
      # With +project:+, remove every managed symlink for this agent.
      # With a skill +name+, remove that skill's adapter entry (legacy).
      #
      # @param name [String, nil]
      # @param project [Project, nil]
      # @return [void]
      def remove(name = nil, project: nil)
        if project
          clear_managed
          return
        end

        raise ArgumentError, "skill name is required" if name.to_s.strip.empty?

        remove_named(name.to_s.strip)
      end

      private

      attr_reader :root

      # @return [Hash{Symbol => String}]
      def adapter_info
        self.class::ADAPTER_INFO
      end

      # @return [Pathname]
      def agent_root
        root.join(adapter_info.fetch(:adapter))
      end

      # @return [Pathname]
      def skills_dir
        agent_root.join(adapter_info.fetch(:directory))
      end

      # @return [Pathname]
      def marker_path
        skills_dir.join(MANAGED_MARKER)
      end

      # @param name [String]
      # @return [Pathname]
      def destination_for(name)
        root.join(
          adapter_info.fetch(:adapter),
          adapter_info.fetch(:directory),
          name
        )
      end

      # @param skill [Skill]
      # @return [String]
      def entry_name(skill)
        "#{skill.name.tr("/", "-")}@#{skill.version}"
      end

      # @param source [String, Pathname]
      # @param destination [String, Pathname]
      # @return [void]
      def link(source, destination)
        write_symlink(Pathname.new(source), Pathname.new(destination))
      end

      # @return [ChangeSet]
      def unavailable_change_set
        ChangeSet.new(added: [], removed: [], kept: [], available: false)
      end

      # @param wanted [Array<Skill>]
      # @param current [Hash{String => Pathname}]
      # @return [ChangeSet]
      def diff(wanted, current)
        added = []
        kept = []
        wanted.each do |skill|
          path = current[skill.label]
          if path && same_target?(path, skill.path)
            kept << skill.label
          else
            added << skill.label
          end
        end
        removed = current.keys - wanted.map(&:label)
        ChangeSet.new(added: added.sort, removed: removed.sort, kept: kept.sort, available: true)
      end

      # @param wanted [Array<Skill>]
      # @param current [Hash{String => Pathname}]
      # @param changeset [ChangeSet]
      # @return [void]
      def apply(wanted, current, changeset)
        FileUtils.mkdir_p(skills_dir)
        write_marker
        changeset.removed.each do |label|
          unlink_managed(current[label])
        end
        wanted.each do |skill|
          next if changeset.kept.include?(skill.label)

          replace_entry(skill, current[skill.label])
        end
      end

      # @param changeset [ChangeSet]
      # @return [Boolean]
      def apply?(changeset)
        return true if changeset.added.any? || changeset.removed.any?

        changeset.kept.any? && !marker_path.file?
      end

      # @param skill [Skill]
      # @param existing [Pathname, nil]
      # @return [void]
      def replace_entry(skill, existing)
        destination = skills_dir.join(entry_name(skill))
        unlink_managed(existing) if existing && existing != destination
        return if destination.exist? && !destination.symlink?

        unlink_managed(destination) if destination.symlink?
        return if destination.exist?

        write_symlink(Pathname.new(skill.path), destination)
      end

      # @return [void]
      def clear_managed
        managed_entries.each_value do |path|
          unlink_managed(path)
        end
        marker_path.unlink if marker_path.file?
      end

      # @param name [String]
      # @return [void]
      def remove_named(name)
        destination = destination_for(name)
        FileUtils.rm_rf(destination) if destination.exist? || destination.symlink?
        prefix = "#{name.tr("/", "-")}@"
        managed_entries.each do |label, path|
          next unless label.start_with?("#{name}@") || path.basename.to_s.start_with?(prefix)

          unlink_managed(path)
        end
      end

      # @return [Hash{String => Pathname}] label => symlink
      def managed_entries
        return {} unless skills_dir.directory?

        skills_dir.children.each_with_object({}) { |child, entries|
          next if child.basename.to_s.start_with?(".")
          next unless child.symlink?

          skill = skill_from_symlink(child)
          next unless skill

          entries[skill.label] = child
        }
      end

      # @param path [Pathname]
      # @return [Skill, nil]
      def skill_from_symlink(path)
        target = resolve_symlink(path)
        relative = relative_to_canonical(target)
        return unless relative

        parts = relative.each_filename.to_a
        return unless parts.size == 3

        Skill.new(
          name: "#{parts[0]}/#{parts[1]}",
          version: parts[2],
          path: target.expand_path
        )
      rescue ArgumentError
        nil
      end

      # @param path [Pathname]
      # @return [Pathname]
      def resolve_symlink(path)
        target = Pathname.new(path.readlink)
        target.absolute? ? target : path.dirname.join(target)
      end

      # @param path [Pathname]
      # @return [Pathname, nil]
      def relative_to_canonical(path)
        canonical = root.join(".ruby-skills").expand_path
        expanded = path.expand_path
        relative = expanded.relative_path_from(canonical)
        return if relative.each_filename.first == ".."

        relative
      rescue ArgumentError
        nil
      end

      # @param link [Pathname]
      # @param source [String, Pathname]
      # @return [Boolean]
      def same_target?(link, source)
        return false unless link.symlink?

        resolve_symlink(link).expand_path == Pathname.new(source).expand_path
      end

      # @param source [Pathname]
      # @param destination [Pathname]
      # @return [void]
      def write_symlink(source, destination)
        FileUtils.mkdir_p(destination.dirname)
        relative = source.expand_path.relative_path_from(destination.dirname.expand_path)
        return if matching_symlink?(destination, relative)

        destination.unlink if destination.symlink?
        return if destination.exist?

        FileUtils.ln_s(relative.to_s, destination.to_s)
      end

      # @param destination [Pathname]
      # @param relative [Pathname]
      # @return [Boolean]
      def matching_symlink?(destination, relative)
        destination.symlink? && destination.readlink.to_s == relative.to_s
      end

      # @param path [Pathname, nil]
      # @return [void]
      def unlink_managed(path)
        return if path.nil?
        return unless path.symlink? || !path.exist?

        path.unlink if path.symlink? || path.file?
      end

      # @return [void]
      def write_marker
        marker_path.write(MARKER_CONTENTS)
      end
    end
  end
end
